const CURRENT_PAGE = "CURRENT_PAGE";
const GET_COUNTRIES = "GET_COUNTRIES";
const GET_COUNTRIE = "GET_COUNTRIE";
const CONTINENT_FILTER_COUNTRIES = "CONTINENT_FILTER_COUNTRIES";
const CONTINENT_FILTER_POPULATION = "CONTINENT_FILTER_POPULATION";
const CONTINENT_FILTER_ALPH = "CONTINENT_FILTER_ALPH";
export { GET_COUNTRIES, GET_COUNTRIE, CONTINENT_FILTER_COUNTRIES, CONTINENT_FILTER_ALPH, CONTINENT_FILTER_POPULATION, CURRENT_PAGE };
